name = "JuliaGendUniv_Types"
uuid = "603251c8-9ed4-4db3-9104-3e0302b27083"
authors = ["Krishna Bhogaonker"]
version = "0.1.0"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
ComponentArrays = "0.14"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
